# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5f2935d87efaf2b7788ea34542caa6a27b826a9eedc5887987fb868260534743607e0121e335141e8d1ccfd9859f00ea7d93045bdc752f5f2d236dcdd17548a

test:
  secret_key_base: 457553eaad5700ba367f8dbe244934cfb4333d664c3fbf0cf8dad4aab503874bae3df31c4a3c1301748527bcf8152316225e0a679b774af60089b26750943ff6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
